---
AWSTemplateFormatVersion: '2010-09-09'
Description: "Example Serverless deployment stack"
Resources:
  ExampleBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicReadWrite
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders:
          - "*"
          AllowedMethods:
          - PUT
          AllowedOrigins:
          - "*"
          MaxAge: '3000'
  ExampleBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ExampleBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: PublicReadGetObject
          Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: ExampleBucket
              - "/*"

Outputs:
  ExampleBucketName:
    Value:
      Ref: ExampleBucket
